apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: bookstore-frontend
